In [3]:
import pandas as pd
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42) # You can use any integer value here. For quiz put 42

# Generate 25 random names for the 'nombre' column
nombres = [f'Estudiante{i}' for i in range(10)]

# Generate 4 columns of random grades between 0 and 5 with two decimal places
# np.random.uniform generates floats between low (inclusive) and high (exclusive)
parciales = np.round(np.random.uniform(0, 5, size=(10, 4)), 2);

# Create the DataFrame
df = pd.DataFrame({
    'nombre': nombres,
    'parcial1': parciales[:, 0],
    'parcial2': parciales[:, 1],
    'parcial3': parciales[:, 2],
    'parcial4': parciales[:, 3]
})

df

        nombre  parcial1  parcial2  parcial3  parcial4
0  Estudiante0      1.87      4.75      3.66      2.99
1  Estudiante1      0.78      0.78      0.29      4.33
2  Estudiante2      3.01      3.54      0.10      4.85
3  Estudiante3      4.16      1.06      0.91      0.92
4  Estudiante4      1.52      2.62      2.16      1.46
5  Estudiante5      3.06      0.70      1.46      1.83
6  Estudiante6      2.28      3.93      1.00      2.57
7  Estudiante7      2.96      0.23      3.04      0.85
8  Estudiante8      0.33      4.74      4.83      4.04
9  Estudiante9      1.52      0.49      3.42      2.20

In [4]:
# Set the 'nombre' column as the index immediately after creation
df = df.set_index('nombre')

# Display the DataFrame
df

             parcial1  parcial2  parcial3  parcial4
nombre
Estudiante0      1.87      4.75      3.66      2.99
Estudiante1      0.78      0.78      0.29      4.33
Estudiante2      3.01      3.54      0.10      4.85
Estudiante3      4.16      1.06      0.91      0.92
Estudiante4      1.52      2.62      2.16      1.46
Estudiante5      3.06      0.70      1.46      1.83
Estudiante6      2.28      3.93      1.00      2.57
Estudiante7      2.96      0.23      3.04      0.85
Estudiante8      0.33      4.74      4.83      4.04
Estudiante9      1.52      0.49      3.42      2.20

In [5]:
# Calcular el percentil 25 de 'parcial1'
L = [i/10 for i in range(1,11)]
percentile_25 = df.quantile(L)
percentile_25

     parcial1  parcial2  parcial3  parcial4
0.1     0.735     0.464     0.271     0.913
0.2     1.372     0.658     0.786     1.352
0.3     1.520     0.756     0.973     1.719
0.4     1.730     0.948     1.276     2.052
0.5     2.075     1.840     1.810     2.385
0.6     2.552     2.988     2.512     2.738
0.7     2.975     3.657     3.154     3.305
0.8     3.020     4.092     3.468     4.098
0.9     3.170     4.741     3.777     4.382
1.0     4.160     4.750     4.830     4.850

In [6]:
def ubicacion(n):
  nota = df.iloc[n,0]
  percentil = 0
  while percentile_25.iloc[percentil, 0] < nota:
    percentil += 1
  return percentil

In [7]:
df.iloc[2,0], ubicacion(2)

(np.float64(3.01), 7)